mpi:
# - nompi
# - mpich
# - openmpi
  - mvapich

mvapich:
  - "4.1 shs_cuda_h*_1*"

c_compiler_version:
  - 13

cxx_compiler_version:
  - 13

fortran_compiler_version:
  - 13

c_stdlib_version:
  - 2.34  # [linux]
