{% set name = "elpa" %}
{% set version = "2021.11.001" %}
{% set build = 2 %}
{% set mpi = mpi or "nompi" %}

# ELPA uses suffixes to allow parallel installation of several versions in the same prefix
{% if mpi == "nompi" %}
{% set elpa_suffix = "_onenode" %}
{% else %}
{% set elpa_suffix = "" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://elpa.mpcdf.mpg.de/software/tarball-archive/Releases/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb361da6c59946661b73e51538d419028f763d7cb9dacf9d8cd5c9cd3fb7802f
  patches:
    - fdep-perl.patch
    - pkgconf.patch
    - check_thread_affinity.patch
    - includedir-suffix.patch

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
  {% if mpi != "nompi" %}
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}
    - {{ pin_subpackage('elpa', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - perl
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]

test:
  requires:
    - pkg-config
  commands:
    - test -f $PREFIX/lib/libelpa{{ elpa_suffix }}${SHLIB_EXT}
    - test -f $PREFIX/lib/libelpa{{ elpa_suffix }}_openmp${SHLIB_EXT}
    - pkg-config {{ name }}{{ elpa_suffix }} --exact-version {{ version }}
    - pkg-config {{ name }}{{ elpa_suffix }}_openmp --exact-version {{ version }}
    - {{ name }}2_print_kernels{{ elpa_suffix }}
    - {{ name }}2_print_kernels{{ elpa_suffix }}_openmp

about:
  home: https://elpa.mpcdf.mpg.de/
  doc_url: https://elpa.mpcdf.mpg.de/documentation/doxygen/ELPA_DOXYGEN_PAGES/ELPA-{{ version }}/html/index.html
  dev_url: https://gitlab.mpcdf.mpg.de/elpa/elpa
  license: LGPL-3.0-only
  license_file:
    - LICENSE
    - COPYING/COPYING
    - COPYING/gpl.txt
    - COPYING/lgpl.txt
  summary: Eigenvalue Solvers for Petaflop-Applications
  description: |
    The computation of selected or all eigenvalues and eigenvectors of a symmetric
    (Hermitian) matrix has high relevance for various scientific disciplines.
    For the calculation of a significant part of the eigensystem typically direct
    eigensolvers are used. For large problems, the eigensystem calculations with
    existing solvers can become the computational bottleneck.

extra:
  recipe-maintainers:
    - awvwgk
